In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import MissingIndicator

In [2]:
features = [[4, 2, 1], 
            [24, 12, 6], 
            [8, 4, 2], 
            [28, 14, 7], 
            [32, 16, -1], 
            [600, 300, 150], 
            [-1, 60, 30], 
            [-1, 4, 1]]

In [3]:
indicator = MissingIndicator(missing_values=-1)

In [4]:
mask_missing_values_only = indicator.fit_transform(features)

mask_missing_values_only

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False],
       [ True, False]])

In [5]:
indicator.features_

array([0, 2])

In [6]:
indicator = MissingIndicator(missing_values=-1, features="all")
mask_all = indicator.fit_transform(features)

mask_all

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [7]:
indicator.features_

array([0, 1, 2])